name: Golang Formatter

on: pull_request

jobs:
  format:
    name: Golang Formatter
    runs-on: ubuntu-latest
    steps:
    - name: Golang Formatter
      uses: sladyn98/auto-go-format@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
